name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest    
    
    steps:
      - name: Execute commands on Hostinger
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/u384149813/domains/marbrestaurant.com/laravel-app
            git pull origin main
            composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader
            php artisan optimize:clear
            php artisan config:cache

            php artisan route:cache
            php artisan view:cache
            rsync -av --delete --exclude=images public/ ../public_html/